//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accomodation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accomodation()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.Reservations = new HashSet<Reservation>();
            this.SentMessages = new HashSet<SentMessage>();
        }
    
        public System.Guid AccomodationId { get; set; }
        public byte Type { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Category { get; set; }
        public byte NoPersons { get; set; }
        public Nullable<byte> Parking { get; set; }
        public Nullable<byte> Wifi { get; set; }
        public Nullable<byte> HB { get; set; }
        public Nullable<byte> TV { get; set; }
        public Nullable<byte> Kitchen { get; set; }
        public Nullable<byte> Bathroom { get; set; }
        public byte Price { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual Accomodation Accomodation1 { get; set; }
        public virtual Accomodation Accomodation2 { get; set; }
    }
}
