//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public System.Guid AccomodationId { get; set; }
        public System.Guid UserId { get; set; }
        public byte RatingMark { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
        public virtual BookingAgencyUser BookingAgencyUser { get; set; }
    }
}
