//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.SentMessages = new HashSet<SentMessage>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid AccomodationId { get; set; }
        public System.DateTime StartPeriod { get; set; }
        public System.DateTime EndPeriod { get; set; }
        public Nullable<byte> Confirmed { get; set; }
        public Nullable<bool> CommentConsumed { get; set; }
        public Nullable<bool> RatingConsumed { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
        public virtual BookingAgencyUser BookingAgencyUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        public virtual ICollection<SentMessage> SentMessages { get; set; }
    }
}
