//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccomodationOwner
    {
        public System.Guid OwnerId { get; set; }
        public System.Guid AccomodationId { get; set; }
    
        public virtual Accomodation Accomodation { get; set; }
    }
}
