//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid ReservationId { get; set; }
        public System.Guid SenderId { get; set; }
        public string Message { get; set; }
        public System.DateTime MessageDate { get; set; }
        public Nullable<byte> MessageSeen { get; set; }
    
        public virtual BookingAgencyUser BookingAgencyUser { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
